[build]
command = """
    apt-get install -y graphviz &&
    wget -q https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz &&
    tar -xzf doxygen-1.13.2.linux.bin.tar.gz &&
    git clone https://github.com/jothepro/doxygen-awesome-css docs/doxygen-awesome-css &&
    ./doxygen-1.13.2/bin/doxygen Doxyfile
  """
publish = "docs/generated/html"
